global:
  environment: dev

replicaCount: 1

image:
  repository: oktbabs
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "micro-sa"

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: chart-example-tls
      hosts:
        - chart-example.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

# -------------------
# Microservices block
# -------------------
services:
  adservice:
    image: adservice
    port: 9555
    targetPort: 9555
    env:
      - name: PORT
        value: "9555"
    readinessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:9555"]
      initialDelaySeconds: 20
      periodSeconds: 15
    livenessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:9555"]
      initialDelaySeconds: 20
      periodSeconds: 15
    resources:
      requests:
        cpu: 200m
        memory: 180Mi
      limits:
        cpu: 300m
        memory: 300Mi

  redis-cart:
    image: redis-cart
    port: 6379
    targetPort: 6379
    env: []
    readinessProbe:
      tcpSocket:
        port: 6379
      periodSeconds: 5
    livenessProbe:
      tcpSocket:
        port: 6379
      periodSeconds: 5
    resources:
      requests:
        cpu: 70m
        memory: 200Mi
      limits:
        cpu: 125m
        memory: 256Mi

  shippingservice:
    image: shippingservice
    port: 50051
    targetPort: 50051
    env:
      - name: PORT
        value: "50051"
      - name: DISABLE_PROFILER
        value: "1"
    readinessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:50051"]
      periodSeconds: 5
    livenessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:50051"]
      periodSeconds: 5
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

  currencyservice:
    image: currencyservice
    port: 7000
    targetPort: 7000
    env:
      - name: PORT
        value: "7000"
      - name: DISABLE_PROFILER
        value: "1"
    readinessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:7000"]
    livenessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:7000"]
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

  loadgenerator:
    image: loadgenerator
    port: 8080
    targetPort: 8080
    env:
      - name: FRONTEND_ADDR
        value: "frontend:80"
      - name: USERS
        value: "10"
    readinessProbe: {}
    livenessProbe: {}
    resources:
      requests:
        cpu: 300m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

  cartservice:
    image: cartservice
    port: 7070
    targetPort: 7070
    env:
      - name: REDIS_ADDR
        value: "redis-cart:6379"
    readinessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
      initialDelaySeconds: 15
    livenessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
      initialDelaySeconds: 15
      periodSeconds: 10
    resources:
      requests:
        cpu: 200m
        memory: 64Mi
      limits:
        cpu: 300m
        memory: 128Mi

  productcatalogservice:
    image: productcatalogservice
    port: 3550
    targetPort: 3550
    env:
      - name: PORT
        value: "3550"
      - name: DISABLE_PROFILER
        value: "1"
    readinessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:3550"]
    livenessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:3550"]
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

  paymentservice:
    image: paymentservice
    port: 50051
    targetPort: 50051
    env:
      - name: PORT
        value: "50051"
      - name: DISABLE_PROFILER
        value: "1"
    readinessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:50051"]
    livenessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:50051"]
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

  frontend:
    image: frontend
    port: 80
    targetPort: 8080
    type: LoadBalancer
    env:
      - name: PORT
        value: "8080"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice:7000"
      - name: CART_SERVICE_ADDR
        value: "cartservice:7070"
      - name: RECOMMENDATION_SERVICE_ADDR
        value: "recommendationservice:8080"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:50051"
      - name: CHECKOUT_SERVICE_ADDR
        value: "checkoutservice:5050"
      - name: AD_SERVICE_ADDR
        value: "adservice:9555"
      - name: ENABLE_PROFILER
        value: "0"
    readinessProbe:
      httpGet:
        path: "/_healthz"
        port: 8080
        httpHeaders:
          - name: "Cookie"
            value: "shop_session-id=x-readiness-probe"
      initialDelaySeconds: 10
    livenessProbe:
      httpGet:
        path: "/_healthz"
        port: 8080
        httpHeaders:
          - name: "Cookie"
            value: "shop_session-id=x-liveness-probe"
      initialDelaySeconds: 10
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

  recommendationservice:
    image: recommendationservice
    port: 8080
    targetPort: 8080
    env:
      - name: PORT
        value: "8080"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"
      - name: DISABLE_PROFILER
        value: "1"
    readinessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:8080"]
      periodSeconds: 5
    livenessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:8080"]
      periodSeconds: 5
    resources:
      requests:
        cpu: 100m
        memory: 220Mi
      limits:
        cpu: 200m
        memory: 450Mi

  checkoutservice:
    image: checkoutservice
    port: 5050
    targetPort: 5050
    env:
      - name: PORT
        value: "5050"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:50051"
      - name: PAYMENT_SERVICE_ADDR
        value: "paymentservice:50051"
      - name: EMAIL_SERVICE_ADDR
        value: "emailservice:5000"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice:7000"
      - name: CART_SERVICE_ADDR
        value: "cartservice:7070"
    readinessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:5050"]
    livenessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:5050"]
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

  emailservice:
    image: emailservice
    port: 5000
    targetPort: 8080
    env:
      - name: PORT
        value: "8080"
      - name: DISABLE_PROFILER
        value: "1"
    readinessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:8080"]
      periodSeconds: 5
    livenessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:8080"]
      periodSeconds: 5
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

  frontend:
    port: 80
    targetPort: 8080
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      hosts:
        - host: shop.example.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: shop-tls
          hosts:
            - shop.example.com

  emailservice:
    port: 5000
    targetPort: 8080
    ingress:
      enabled: true
      className: nginx
      annotations: {}
      hosts:
        - host: mail.example.com
          paths:
            - path: /
              pathType: Prefix
      tls: []

