{{- range $name, $svc := .Values.services }}
{{- if and $svc.ingress $svc.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}-ingress
  labels:
    app: {{ $name }}
  {{- if $svc.ingress.annotations }}
  annotations:
    {{- range $key, $val := $svc.ingress.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if $svc.ingress.className }}
  ingressClassName: {{ $svc.ingress.className }}
  {{- end }}
  rules:
    {{- range $host := $svc.ingress.hosts }}
    - host: {{ $host.host }}
      http:
        paths:
          {{- range $path := $host.paths }}
          - path: {{ $path.path }}
            pathType: {{ $path.pathType }}
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $svc.port }}
          {{- end }}
    {{- end }}
  {{- if $svc.ingress.tls }}
  tls:
    {{- range $tls := $svc.ingress.tls }}
    - secretName: {{ $tls.secretName }}
      hosts:
        {{- range $host := $tls.hosts }}
        - {{ $host }}
        {{- end }}
    {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}

