{{- range $name, $svc := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    environment: {{ $.Values.global.environment }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: {{ $.Values.image.repository }}/{{ $name }}:{{ $.Values.image.tag }}
          ports:
            - containerPort: {{ $svc.targetPort }}
          env:
            {{- toYaml $svc.env | nindent 12 }}
          {{- if $svc.readinessProbe }}
          readinessProbe:
            {{- toYaml $svc.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if $svc.livenessProbe }}
          livenessProbe:
            {{- toYaml $svc.livenessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $svc.resources | nindent 12 }}
---
{{- end }}

